name: helloworld
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.15.5
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  firebase_storage: ^11.6.6
  font_awesome_flutter: ^10.7.0
  flutter:
    sdk: flutter
  mockito: ^5.4.4
  lib: ^0.0.3
  shared_preferences: ^2.2.2
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_database_mocks: ^0.6.1
  firebase_auth_mocks: ^0.13.0
  flutter_lints: ^3.0.2
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/explorer.png
    - assets/welcome.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
