// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOYH7W81y5YwfnXRG3lqb0wlhfqJoP4ik',
    appId: '1:449861433869:web:7f08c0d9781e071d9d7344',
    messagingSenderId: '449861433869',
    projectId: 'gugu-36085',
    authDomain: 'gugu-36085.firebaseapp.com',
    storageBucket: 'gugu-36085.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWIjc77rGqlmxx0Ru11QEITRQFbB3w6bk',
    appId: '1:449861433869:android:a4a919c2692e07529d7344',
    messagingSenderId: '449861433869',
    projectId: 'gugu-36085',
    storageBucket: 'gugu-36085.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANBLHqssadk-t8L7dRvW-gTdbcGsthbBI',
    appId: '1:449861433869:ios:ee939532fdb3539f9d7344',
    messagingSenderId: '449861433869',
    projectId: 'gugu-36085',
    storageBucket: 'gugu-36085.appspot.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
